WebApplication1/Models/Dispositivo.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

[AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
public sealed class DecimalPrecisionAttribute : Attribute
{
    public DecimalPrecisionAttribute(byte precision, byte scale)
    {
        Precision = precision;
        Scale = scale;
    }

    public byte Precision { get; set; }
    public byte Scale { get; set; }
}

namespace WebApplication1.Models
{
    public enum EstatusDispositivos
    {
        Apagado = 0,
        Encendido = 1
    }

    public class Dispositivo
    {
        [Key]
        public int Id { get; set; }
        
        [MaxLength(20)]
        public string? Nombre { get; set; }

        public DateTime FechaCreacion{get;set;}=DateTime.Now;
        
        [DecimalPrecision(18, 10)]
        [Column(TypeName = "decimal(18, 10)")]
        public decimal Latitud { get; set; }
        [Column(TypeName = "decimal(18, 10)")]
         [DecimalPrecision(18, 10)]
        public decimal Longitud { get; set; }
        public string? Responsable { get; set; }
        public string? Zona { get; set; }
        public string? Descripcion { get; set; }
        public int Prioridad { get; set; }
        public EstatusDispositivos Estatus { get; set; }
        public decimal LitrosRegistrados { get; set; }
    }
}

WebApplication1/Controllers/DispositivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using WebApplication1.Models;
using WebApplication1.Hubs;
namespace WebApplication1.Controllers
{
    public class DispositivoController : Controller

    {
        private readonly DispositivoDBContext _dbContex;
        private readonly IHubContext<MyHub> _hubContext;
        public DispositivoController(DispositivoDBContext dbContext, IHubContext<MyHub> hubContext)
        {
            _dbContex = dbContext;
            _hubContext = hubContext;
        }
        public IActionResult Index()
        {
            // Recuperar todos los dispositivos
            var dispositivos = _dbContex.Dispositivos.ToList();

            // Datos para la gráfica de litros
            ViewBag.Nombres = dispositivos.Select(d => d.Nombre).ToList();
            ViewBag.Litros = dispositivos.Select(d => d.LitrosRegistrados).ToList();

            // Datos para la gráfica de estado (Apagado/Encendido)
            var dispositivosApagados = _dbContex.Dispositivos.Count(d => d.Estatus == EstatusDispositivos.Apagado);
            var dispositivosEncendidos = _dbContex.Dispositivos.Count(d => d.Estatus == EstatusDispositivos.Encendido);

            ViewBag.DispositivosApagados = dispositivosApagados;
            ViewBag.DispositivosEncendidos = dispositivosEncendidos;

            return View(dispositivos);
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Dispositivo dispositivo) //Crear Dispositivo (inserccion en la bd)
        {
            if (ModelState.IsValid)
            {

                _dbContex.Dispositivos.Add(dispositivo);
                _dbContex.SaveChanges();

                _hubContext.Clients.All.SendAsync("DispositivoAgregado", "Nuevo dispositivo agregado!");
               /*  _hubContext.Clients.All.SendAsync("DispositivoAgregado", dispositivo.Id, dispositivo.Latitud, dispositivo.Longitud); */

                return RedirectToAction("Index");
            }

            return View(dispositivo);
        }
        [HttpPost]
        public IActionResult Delete(int id)    //Elimina filas mediante boton
        {
            var dispositivo = _dbContex.Dispositivos.Find(id);
            if (dispositivo != null)
            {
                string nombreDelDispositivoEliminado = dispositivo.Nombre;
                DateTime fechaActual = DateTime.Now;
                _dbContex.Dispositivos.Remove(dispositivo);
                _dbContex.SaveChanges();

                _hubContext.Clients.All.SendAsync("DispositivoEliminado", nombreDelDispositivoEliminado, fechaActual.ToString("dd/MM/yyyy HH:mm:ss"));
                // Asumiendo que tienes una instancia de IHubContext


            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult CambiarEstado(int id)
        {
            var dispositivo = _dbContex.Dispositivos.FirstOrDefault(d => d.Id == id);
            if (dispositivo == null)
            {
                return NotFound();
            }

            dispositivo.Estatus = dispositivo.Estatus == EstatusDispositivos.Apagado ? EstatusDispositivos.Encendido : EstatusDispositivos.Apagado;
            _dbContex.SaveChanges();

            _hubContext.Clients.All.SendAsync("EstatusCambiado", dispositivo.Nombre, dispositivo.Estatus.ToString());
            _hubContext.Clients.All.SendAsync("ActualizarTablaDispositivos");

            var todosApagados = !_dbContex.Dispositivos.Any(d => d.Estatus == EstatusDispositivos.Encendido);
            if (todosApagados)
            {
                Console.WriteLine("Todos los dispositivos están apagados.");
                _hubContext.Clients.All.SendAsync("TodosApagados", "¡Atención! Todos los dispositivos están apagados. Por favor encienda al menos uno.");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public JsonResult GetAllDispositivos()
        {
            var dispositivos = _dbContex.Dispositivos.ToList();
            return Json(dispositivos);
        }

        [HttpGet]
        public JsonResult ObtenerDatosGraficaEstatus()
        {
            var dispositivosApagados = _dbContex.Dispositivos.Count(d => d.Estatus == EstatusDispositivos.Apagado);
            var dispositivosEncendidos = _dbContex.Dispositivos.Count(d => d.Estatus == EstatusDispositivos.Encendido);

            return Json(new { dispositivosApagados, dispositivosEncendidos });
        }
        [HttpGet]
        public JsonResult ObtenerDatosGraficaLitros()
        {
            var dispositivos = _dbContex.Dispositivos.ToList();
            var nombres = dispositivos.Select(d => d.Nombre).ToList();
            var litrosPorDispositivo = dispositivos.Select(d => d.LitrosRegistrados).ToList();

            return Json(new { nombres, litrosPorDispositivo });
        }

        [HttpGet]
        public JsonResult GetTotalLitros()
        {
            var totalLitros = _dbContex.Dispositivos.Sum(d => d.LitrosRegistrados);
            return Json(new { totalLitros });
        }

     

    }
}

WebApplication1/Views/Dispositivo/Create.cshtml
@model WebApplication1.Models.Dispositivo

@{
    ViewBag.Title = "Agregar Dispositivo";
}

<h2>@ViewBag.Title</h2>
  
@using (Html.BeginForm("Create", "Dispositivo", FormMethod.Post))
{
    <div class="form-group">
        <label>Nombre:</label>
        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Latitud:</label>
        
        @Html.TextBoxFor(model => model.Latitud, new { @class = "form-control", @id = "campoLatitud" })


    </div>

    <div class="form-group">
        <label>Longitud:</label>
       @Html.TextBoxFor(model => model.Longitud, new { @class = "form-control", @id = "campoLongitud" })
    </div>

    <div class="form-group">
        <label>Descripción:</label>
        @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Prioridad:</label>
        @Html.DropDownListFor(model => model.Prioridad, 
            Enumerable.Range(1,5).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }).ToList(),
            "Seleccione la prioridad", new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Estatus:</label>
        @Html.DropDownListFor(model => model.Estatus, new List<SelectListItem> {
            new SelectListItem { Text = "Encendido", Value = "Encendido" },
            new SelectListItem { Text = "Apagado", Value = "Apagado" }
        }, "Seleccione el estatus", new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Litros Registrados:</label>
        @Html.TextBoxFor(model => model.LitrosRegistrados, new { @class = "form-control" })
    </div>

   <div class="form-group">
        <label>Responsable:</label>
        @Html.DropDownListFor(model => model.Responsable, new List<SelectListItem> {
            new SelectListItem { Text = "Emmanuel Hernandez", Value = "Emmanuel Hernandez" },
            new SelectListItem { Text = "Enrique De Jesus ", Value = "Enrique De Jesus" },
            new SelectListItem { Text = "Marco Antonio Aguilar", Value = "Marco Antonio Aguilar" },
            new SelectListItem { Text = "Luisa Peralta", Value = "Luisa Peralta" }
        }, "Seleccione un responsable", new { @class = "form-control" })
    </div>

      <div class="form-group">
        <label>Zona:</label>
        @Html.DropDownListFor(model => model.Zona, 
            Enumerable.Range(1,10).Select(i => new SelectListItem { Text = "Zona " + i, Value = "Zona " + i }).ToList(),
            "Seleccione la zona", new { @class = "form-control" })
    </div>


    <button type="submit" class="btn btn-primary">Agregar</button>

    
}
<script>
    document.addEventListener("DOMContentLoaded", function() {
    var lat = localStorage.getItem('latitud');
    var lon = localStorage.getItem('longitud');

    if (lat && lon) {
        document.getElementById('campoLatitud').value = lat;
        document.getElementById('campoLongitud').value = lon;
    }
});

</script>

WebApplication1/Views/Dispositivo/Index.cshtml
@model IEnumerable<WebApplication1.Models.Dispositivo>
{
    Layout= null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    @* <script src="~/lib/signalr/signalr.js"></script> *@
    <script src="~/lib/signalr/signalr.js"></script>
    @* <script src="~/js/site.js"></script> *@


    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />


    <meta name="viewport" content="width=device-width" />
    <title>Lista de Dispositivos</title>
</head>

<body>
    <h1 style="text-align: center;">CONTROL DE AGUA </h1>
    <h2 >Ubicación  de llaves</h2>
    <div id="mapa" style="width:600px; height:400px;"></div>
    @* <script src="~/js/site.js"></script> *@
    <script src="~/lib/signalr/signalr.js"></script>y
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    @* MAPA *@

    <script>


        var map = L.map('mapa').setView([19.815852302707444, -97.36644780597221], 18);
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 18,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);

        // Añade los marcadores de los dispositivos al mapa
        @foreach (var dispositivo in Model)
        {
            <text>
                    L.marker([@dispositivo.Latitud, @dispositivo.Longitud]).addTo(map)
                    .bindPopup('@dispositivo.Nombre');
            </text>
        }

            map.on('click', function (e) {
                var lat = e.latlng.lat;
                var lon = e.latlng.lng;

                localStorage.setItem('latitud', lat);
                localStorage.setItem('longitud', lon);
                window.location.href = '/Dispositivo/Create';
            });

    </script>



    <div class="container mt-5">
        <h2>Dispositivos</h2>
        <p>
            @Html.ActionLink("Agregar Dispositivo", "Create", null, new { @class = "btn btn-primary mb-3" })
        </p>
        <table class="table table-striped table-bordered table-sm">

            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Latitud</th>
                    <th>Longitud</th>
                    <th>Descripción</th>
                    <th>Prioridad</th>
                    <th>Estatus</th>
                    <th>Litros Registrados</th>
                    <th>Fecha de Creacion</th>
                    <th>Responsable</th>
                    <th>Zona</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var dispositivo in Model)
                {
                    <tr>
                        <td>@dispositivo.Id</td>
                        <td>@dispositivo.Nombre</td>
                        <td>@dispositivo.Latitud</td>
                        <td>@dispositivo.Longitud</td>
                        <td>@dispositivo.Descripcion</td>
                        <td>@dispositivo.Prioridad</td>
                        <td>@dispositivo.Estatus</td>
                        <td>@dispositivo.LitrosRegistrados</td>
                        <td>@dispositivo.FechaCreacion</td>
                        <td>@dispositivo.Responsable</td>
                        <td>@dispositivo.Zona</td>
                        <td>
                            <form action="@Url.Action("Delete", "Dispositivo", new { id = dispositivo.Id })" method="post"
                                style="display:inline">
                                <input type="submit" value="Eliminar" class="btn btn-danger btn-sm"
                                    onclick="return confirm('¿Estás seguro de que deseas eliminar este dispositivo?');" />
                            </form>
                            <form method="post" asp-action="CambiarEstado" style="display:inline">
                                <input type="hidden" name="id" value="@dispositivo.Id" />
                                <input type="submit" value="Cambiar Estado" class="btn btn-warning btn-sm" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="graficas-wrapper">


            <div class="grafica-container">
                <canvas id="litrosTotalChart" width="100" height="50"></canvas>
            </div>

            <div class="grafica-container">
                <canvas id="litrosChart" width="100" height="50"></canvas>
            </div>
            <div id="estatusChartContainer">
                <canvas id="estatusChart" width="80" height="40"></canvas>
            </div>

        </div>

    </div>


    <script>
        var ctx = document.getElementById('litrosChart').getContext('2d');
        var litrosChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: @Html.Raw(Json.Serialize(ViewBag.Nombres)),
                datasets: [{
                    label: 'Litros Registrados Por Dispositivo',
                    data: @Html.Raw(Json.Serialize(ViewBag.Litros)),
                    backgroundColor: 'rgba(75, 192, 192, 0.2)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>


    <script>
        var ctx2 = document.getElementById('estatusChart').getContext('2d');
        var estatusChart = new Chart(ctx2, {
            type: 'pie', // gráfico de tipo pie
            data: {
                labels: ["Apagados", "Encendidos"],
                datasets: [{
                    label: 'Estatus de Dispositivos',
                    data: [@Html.Raw(Json.Serialize(ViewBag.DispositivosApagados)), @Html.Raw(Json.Serialize(ViewBag.DispositivosEncendidos))],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',  // Color para Apagados
                        'rgba(54, 162, 235, 0.2)'  // Color para Encendidos
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)'
                    ],
                    borderWidth: 1
                }]
            }
        });

    </script>

    <div id="contenedor"> </div>




</body>

</html>