WebApplication1/Models/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using System.Security.Claims;

namespace WebApplication1.Models
{
    public class UsuariosController : Controller
    {
            private readonly DispositivoDBContext context;

        public UsuariosController(DispositivoDBContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Usuarios u)
        {

            if (ModelState.IsValid)
            {
                Usuarios utemp = context.Usuarios.Include(x => x.Roles)
                                .FirstOrDefault(x => x.Usuario == u.Usuario
                                && x.Password == u.Password)!;
                if (utemp != null)
                {
                    List<Claim> claims = new List<Claim>();
                    claims.Add(new Claim("username", utemp.Usuario!));
                    claims.Add(new Claim(ClaimTypes.NameIdentifier, utemp.Usuario!));
                    claims.Add(new Claim(ClaimTypes.Role, utemp.Roles.Rol));
                    ClaimsIdentity identity = new ClaimsIdentity(claims,
                        CookieAuthenticationDefaults.AuthenticationScheme);
                    ClaimsPrincipal principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(principal);
                    return RedirectToAction("Index", "Dispositivo");
                }
            }
            ViewBag.Error = "Usuario y/o password incorrectos";
            return View(u);
        }

        public IActionResult NoPermitido()
        {
            return View();
        }

        public async Task<IActionResult> CerrarSesion(){
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
            


    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Control</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CONTROL DE AGUA
                    TEZIUTLAN</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>

                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                            <a class="nav-link active" asp-action="CerrarSesion" asp-controller="Usuarios">Cerrar Sesión</a>
                            </li>


                        } 
                        else
                        {
                            <li class="nav-item">
                            <a class="nav-link active" asp-action="Login" asp-controller="Usuarios">Iniciar Sesión</a>
                        </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;Examen-ProgramacionWen Hibrida Unidad 2 Alumno: Enrique De Jesus Garcia - <a asp-area=""
                asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>